server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kakao
    username: kakao
    password: #antlstkWKd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    output:
      ansi:
        enabled: always
  thymeleaf:
    prefix:classpath: templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0
logging:
  level:
    org.hibernate.type: trace